### ISSUE TITLE
Zip File for Data

### ISSUE THREAD

**Issue by knarfamlap** [shotakoyama/fcgwork#1]
Hi,

Thanks for sharing your work! Do you happen to have the zip file with the data splits? The shared task seems to be closed but we would like to run experiments on the data. We would really appreciate if you could share it! 

Thanks,
Frank

**Comment by nymwa** [comment]
Thank you for your question.

The dataset is now not open, and is released only for the task participants.
I cannot send the data on own judgement.

I think that asking to task organizers is the best way to get the dataset.
Please contact them. You can find their address in the task webcite.
I think that they are kind to you and will respond as much as possible.
